volumes:
  waf_dir:


services:
  transform:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - waf_dir:/usr/local/wafs
    restart: unless-stopped
    secrets:
      - waf_push_token
    healthcheck:
      test: ["CMD", "supervisorctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

secrets:
  waf_push_token:
    file: ./.github_token