apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: sage-ro
    kind: SecretStore
  target:
    name: secrets-transform
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    #  Allows writes to WAF repos on github
    - secretKey: WAF_PUSH_TOKEN
      remoteRef:
        key: sage/sage-iso-transform
        property: WAF_PUSH_TOKEN
