apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ~/bin/kompose --file docker-compose.yml convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: transform
  name: transform
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transform
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ~/bin/kompose --file docker-compose.yml convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: transform
    spec:
      containers:
        - image: "{{ .Values.webapp.images.transform }}:{{ .Values.webapp.tag }}"
          livenessProbe:
            exec:
              command:
                - supervisorctl
                - status
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: transform
          volumeMounts:
            - mountPath: /usr/local/wafs
              name: transform-waf-dir
          env:
            - name: WAF_PUSH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets-transform
                  key: WAF_PUSH_TOKEN
            - name: TZ
              value: "America/Denver"
      restartPolicy: Always
      volumes:
        - name: transform-waf-dir
          persistentVolumeClaim:
            claimName: transform-waf-dir
