apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: waf-dir
  name: waf-dir
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephfs
  resources:
    requests:
      storage: 5Gi
