webapp:
  name: iso-transform
  tls:
    fqdn: iso-transform.data-commons.k8s.ucar.edu
    secretName: incommon-cert-sage-ckandev
  images:
    transform: ghcr.io/ncar/sage-iso-transform
  tag: 2025-12-02.17.15
